### ISSUE TITLE
Crontab Jobs being run twice at expected time

### ISSUE THREAD

**Issue by jgerry2002** [sibson/redbeat#91] opened 2018-05-16 14:17 UTC
I am trying to use redbeat with a test project as I am trying to integrate crontab jobs at specific times via Celery which is a core requirement of a project I am working on.

I liked the concept of storing these jobs in real time in Redis, as it offers a resilient way to ensure jobs stay in the scheduler and are picked up as configuration changes in near real time.

I am using the example configuration file from your project.

If I enter a job using the redbeat scheduler jobs are fired off twice at the expected time vs once:

interval = celery.schedules.crontab(minute=2, hour=14)
entry = RedBeatSchedulerEntry('test task 4', 'tasksalt.example', interval, args=['testarg1', 'testarg2'],app=app)
entry.save()

Beat shows:
[2018-05-16 10:01:55,672: INFO/MainProcess] Scheduler: Sending due task test task 4 (tasksalt.example)
[2018-05-16 10:01:55,705: DEBUG/MainProcess] tasksalt.example sent. id->2d404bc8-24d6-49c9-8312-62be48377e08
[2018-05-16 10:01:55,705: DEBUG/MainProcess] beat: Waking up in 4.33 seconds.
[2018-05-16 10:02:00,037: DEBUG/MainProcess] beat: Extending lock...
[2018-05-16 10:02:00,038: DEBUG/MainProcess] Selecting tasks
[2018-05-16 10:02:00,039: INFO/MainProcess] Loading 1 tasks
[2018-05-16 10:02:00,041: INFO/MainProcess] Scheduler: Sending due task test task 4 (tasksalt.example)
[2018-05-16 10:02:00,043: DEBUG/MainProcess] tasksalt.example sent. id->fe15ba6e-c29a-4756-82c6-d0cf96d032d2
[2018-05-16 10:02:00,043: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2018-05-16 10:02:05,049: DEBUG/MainProcess] beat: Extending lock...
[2018-05-16 10:02:05,050: DEBUG/MainProcess] Selecting tasks

Celery shows the job being executed twice. I've tried to change the pooling interval both longer and shorter and it makes no difference.

I also tried a once an hour job via crontab at a particular minute, which fired off twice, then ended up on a schedule of 1 time per hour after that. Is there some sort of initial evaluation / state that is being missed? It appears that the job may be ok after its first run.

**Comment by jgerry2002** [comment] 2018-05-16 17:59
Further - it appears you can work around the issue by entering a job, allowing it to run once, then changing the parameters and it will run in the schedule as requested after that. As long as the name is the same its treated as the same job.

Also setting app.conf.CELERY_ALWAYS_EAGER=False will also prevent jobs from overwhelming the queue on a restart next time.

**Comment by WesDowney** [comment] 2018-05-16 19:38
This seems to be the same as issue #79

**Comment by jgerry2002** [comment] 2018-05-16 21:13
Yup, it sure is the same issue. I was trying to dig into the code a bit to try to figure out what exactly the RedisScheduler looks at during the initial run, but its not obvious to me (yet).  This project does 90% of what I need it to even in this state as I can for now just set interval timing on jobs (every 23 hours or something vs exact time). I will try to work around this and hope the author can look into the issue a bit more. Easy dynamic scheduling of large regularly occurring jobs is my goal with some ability to add and subtract from a web interface as needed.

**Comment by sibson** [comment] 2018-07-25 14:02
I'm closing this as a duplicate of #79, there is additional information available in that issue.

**Closed by sibson** 2018-07-25 14:02 UTC
